### ISSUE TITLE
Exception from Deps afterFlush function function: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dennismonsewicz** [andreioprisan/meteor-bootstrap3-wysihtml5#6]
I am receiving the error in the title when calling to the plugin like so:

```
Template.postEdit.rendered = function() {
  $('textarea').wysihtml5();
}
```

I am using Meteor v0.8.0.1

**Comment by ChihChengLiang** [comment]
same issue. How do you resolve this?

**Comment by selasi** [comment]
I got this error:
`$(...).wysihtml5 is not a function`
Am using Meteor v.0.8.3

Any help please?
